# Generated by Django 3.0.2 on 2020-03-21 10:05

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=mirage.fields.EncryptedTextField(unique=True),
        ),
    ]
