# Generated by Django 3.0.2 on 2020-03-21 18:47

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200322_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=mirage.fields.EncryptedTextField(),
        ),
    ]
